<?php

namespace Database\Seeders;

use App\Models\CategoryProduct;
use App\Models\Collections;
use App\Models\Material;
use App\Models\Product;
use App\Models\ProductVariant;
use App\Models\SizeGuide;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $this->call([
            CategoryProductSeeder::class,
            CollectionSeeder::class,
            ProductAttributeSeeder::class,
            SizeGuideSeeder::class,
        ]);

        $categories = CategoryProduct::query()
            ->get()
            ->keyBy('slug');

        $collections = Collections::query()
            ->get()
            ->keyBy('slug');

        $materials = Material::query()
            ->whereIn('material', [
                'Nylon Ripstop',
                'Coated Polyester',
                'Polyester Fleece',
                'Recycled Polyester',
                'Quick-Dry Mesh',
                'Stretch Nylon',
                'Elastane',
                'Merino Wool Blend',
            ])
            ->get()
            ->keyBy('material');

        $sizeGuides = SizeGuide::query()
            ->whereIn('name', ['Tops Standard', 'Outerwear Standard', 'Pants Standard'])
            ->get()
            ->keyBy('name');

        $products = [
            [
                'name' => 'Alpine Shield Jacket',
                'slug' => 'alpine-shield-jacket',
                'category_slug' => 'jackets',
                'collection_slug' => 'alpine-core',
                'size_guide_name' => 'Outerwear Standard',
                'description' => 'Jaket shell ringan untuk hujan dan angin dengan feel teknikal yang nyaman dipakai harian.',
                'material_names' => ['Nylon Ripstop', 'Coated Polyester'],
                'gender' => 'unisex',
                'weight' => 420,
                'temperature' => 4,
                'intensity' => 'high',
                'insulation' => 72,
                'breathability' => 88,
                'is_active' => true,
                'images' => [
                    [
                        'image' => 'products/alpine-shield-primary.svg',
                        'is_primary' => true,
                        'is_hover' => false,
                    ],
                ],
                'variants' => [
                    ['sku' => 'ASH-JKT-S', 'size' => 'S', 'price' => 749000, 'stock' => 12],
                    ['sku' => 'ASH-JKT-M', 'size' => 'M', 'price' => 749000, 'stock' => 10],
                    ['sku' => 'ASH-JKT-L', 'size' => 'L', 'price' => 749000, 'stock' => 8],
                ],
            ],
            [
                'name' => 'Summit Fleece Zip',
                'slug' => 'summit-fleece-zip',
                'category_slug' => 'fleece',
                'collection_slug' => 'alpine-core',
                'size_guide_name' => 'Outerwear Standard',
                'description' => 'Mid-layer fleece hangat dengan zipper penuh, cocok untuk layering di suhu sejuk.',
                'material_names' => ['Polyester Fleece', 'Recycled Polyester'],
                'gender' => 'unisex',
                'weight' => 360,
                'temperature' => 8,
                'intensity' => 'low',
                'insulation' => 80,
                'breathability' => 70,
                'is_active' => true,
                'images' => [
                    [
                        'image' => 'products/summit-fleece-primary.svg',
                        'is_primary' => true,
                        'is_hover' => false,
                    ],
                ],
                'variants' => [
                    ['sku' => 'SMF-FLC-S', 'size' => 'S', 'price' => 529000, 'stock' => 15],
                    ['sku' => 'SMF-FLC-M', 'size' => 'M', 'price' => 529000, 'stock' => 14],
                    ['sku' => 'SMF-FLC-L', 'size' => 'L', 'price' => 529000, 'stock' => 9],
                ],
            ],
            [
                'name' => 'Trail Sprint Tee',
                'slug' => 'trail-sprint-tee',
                'category_slug' => 'tops',
                'collection_slug' => 'trail-motion',
                'size_guide_name' => 'Tops Standard',
                'description' => 'Kaos quick-dry untuk aktivitas outdoor intensitas tinggi dengan bahan cepat kering.',
                'material_names' => ['Quick-Dry Mesh', 'Recycled Polyester'],
                'gender' => 'unisex',
                'weight' => 180,
                'temperature' => 22,
                'intensity' => 'high',
                'insulation' => 25,
                'breathability' => 92,
                'is_active' => true,
                'images' => [
                    [
                        'image' => 'products/trail-sprint-primary.svg',
                        'is_primary' => true,
                        'is_hover' => false,
                    ],
                ],
                'variants' => [
                    ['sku' => 'TRL-TEE-S', 'size' => 'S', 'price' => 249000, 'stock' => 22],
                    ['sku' => 'TRL-TEE-M', 'size' => 'M', 'price' => 249000, 'stock' => 18],
                    ['sku' => 'TRL-TEE-L', 'size' => 'L', 'price' => 249000, 'stock' => 13],
                ],
            ],
            [
                'name' => 'Ridge Cargo Pants',
                'slug' => 'ridge-cargo-pants',
                'category_slug' => 'pants',
                'collection_slug' => 'trail-motion',
                'size_guide_name' => 'Pants Standard',
                'description' => 'Celana trail dengan potongan tapered, stretch ringan, dan saku utilitas untuk perlengkapan kecil.',
                'material_names' => ['Stretch Nylon', 'Elastane'],
                'gender' => 'pria',
                'weight' => 510,
                'temperature' => 18,
                'intensity' => 'high',
                'insulation' => 40,
                'breathability' => 76,
                'is_active' => true,
                'images' => [
                    [
                        'image' => 'products/ridge-cargo-primary.svg',
                        'is_primary' => true,
                        'is_hover' => false,
                    ],
                ],
                'variants' => [
                    ['sku' => 'RDG-PNT-30', 'size' => '30', 'price' => 459000, 'stock' => 11],
                    ['sku' => 'RDG-PNT-32', 'size' => '32', 'price' => 459000, 'stock' => 12],
                    ['sku' => 'RDG-PNT-34', 'size' => '34', 'price' => 459000, 'stock' => 7],
                ],
            ],
            [
                'name' => 'Commuter Windbreaker',
                'slug' => 'commuter-windbreaker',
                'category_slug' => 'jackets',
                'collection_slug' => 'city-commute',
                'size_guide_name' => 'Outerwear Standard',
                'description' => 'Windbreaker harian dengan look clean dan packable untuk mobilitas kota saat cuaca berubah.',
                'material_names' => ['Coated Polyester', 'Nylon Ripstop'],
                'gender' => 'wanita',
                'weight' => 290,
                'temperature' => 16,
                'intensity' => 'low',
                'insulation' => 34,
                'breathability' => 74,
                'is_active' => true,
                'images' => [
                    [
                        'image' => 'products/commuter-windbreaker-primary.svg',
                        'is_primary' => true,
                        'is_hover' => false,
                    ],
                ],
                'variants' => [
                    ['sku' => 'CMT-WDB-S', 'size' => 'S', 'price' => 399000, 'stock' => 16],
                    ['sku' => 'CMT-WDB-M', 'size' => 'M', 'price' => 399000, 'stock' => 14],
                    ['sku' => 'CMT-WDB-L', 'size' => 'L', 'price' => 399000, 'stock' => 10],
                ],
            ],
            [
                'name' => 'Daily Merino Base Layer',
                'slug' => 'daily-merino-base-layer',
                'category_slug' => 'tops',
                'collection_slug' => 'city-commute',
                'size_guide_name' => 'Tops Standard',
                'description' => 'Base layer tipis berbahan merino blend yang lembut, breathable, dan nyaman dipakai seharian.',
                'material_names' => ['Merino Wool Blend'],
                'gender' => 'unisex',
                'weight' => 210,
                'temperature' => 14,
                'intensity' => 'low',
                'insulation' => 48,
                'breathability' => 82,
                'is_active' => true,
                'images' => [
                    [
                        'image' => 'products/daily-merino-primary.svg',
                        'is_primary' => true,
                        'is_hover' => false,
                    ],
                ],
                'variants' => [
                    ['sku' => 'DLY-MRN-S', 'size' => 'S', 'price' => 329000, 'stock' => 18],
                    ['sku' => 'DLY-MRN-M', 'size' => 'M', 'price' => 329000, 'stock' => 15],
                    ['sku' => 'DLY-MRN-L', 'size' => 'L', 'price' => 329000, 'stock' => 12],
                ],
            ],
        ];

        $products = array_merge($products, $this->additionalProducts());

        foreach ($products as $item) {
            $materialIds = collect($item['material_names'])
                ->map(fn (string $name) => $materials[$name]->id ?? null)
                ->filter()
                ->values()
                ->all();

            $product = Product::query()->updateOrCreate(
                ['slug' => $item['slug']],
                [
                    'category_id' => $categories[$item['category_slug']]->id,
                    'collection_id' => $collections[$item['collection_slug']]->id,
                    'size_guide_id' => $sizeGuides[$item['size_guide_name']]->id ?? null,
                    'name' => $item['name'],
                    'description' => $item['description'],
                    'material' => $materialIds,
                    'gender' => $item['gender'],
                    'weight' => $item['weight'],
                    'temperature' => $item['temperature'],
                    'intensity' => $item['intensity'],
                    'insulation' => $item['insulation'],
                    'breathability' => $item['breathability'],
                    'is_active' => $item['is_active'],
                ],
            );

            foreach ($item['images'] as $image) {
                $product->images()->updateOrCreate(
                    ['image' => $image['image']],
                    [
                        'is_primary' => $image['is_primary'],
                        'is_hover' => $image['is_hover'],
                    ],
                );
            }

            foreach ($item['variants'] as $variant) {
                ProductVariant::query()->updateOrCreate(
                    ['sku' => $variant['sku']],
                    [
                        'product_id' => $product->id,
                        'size' => $variant['size'],
                        'price' => $variant['price'],
                        'stock' => $variant['stock'],
                    ],
                );
            }
        }
    }

    private function additionalProducts(): array
    {
        return [
            $this->buildProduct([
                'name' => 'Stormveil Rain Jacket',
                'slug' => 'stormveil-rain-jacket',
                'category_slug' => 'rain-jackets',
                'collection_slug' => 'monsoon-ready',
                'size_guide_name' => 'Outerwear Standard',
                'description' => 'Jaket hujan ringan dengan konstruksi shell rapat untuk perjalanan harian dan hiking saat cuaca cepat berubah.',
                'material_names' => ['Nylon Ripstop', 'Coated Polyester'],
                'gender' => 'unisex',
                'weight' => 395,
                'temperature' => 8,
                'intensity' => 'high',
                'insulation' => 36,
                'breathability' => 86,
                'image' => 'products/alpine-shield-primary.svg',
                'sku_prefix' => 'SVRJ',
                'price' => 699000,
                'stocks' => [14, 11, 8],
            ]),
            $this->buildProduct([
                'name' => 'Glacier Loft Jacket',
                'slug' => 'glacier-loft-jacket',
                'category_slug' => 'down-jackets',
                'collection_slug' => 'glacier-transit',
                'size_guide_name' => 'Outerwear Standard',
                'description' => 'Outerwear hangat untuk cuaca dingin dengan feel ringan dan nyaman dipakai sebagai lapisan utama.',
                'material_names' => ['Nylon Ripstop', 'Recycled Polyester'],
                'gender' => 'unisex',
                'weight' => 540,
                'temperature' => 2,
                'intensity' => 'low',
                'insulation' => 88,
                'breathability' => 54,
                'image' => 'products/alpine-shield-primary.svg',
                'sku_prefix' => 'GLJ',
                'price' => 899000,
                'stocks' => [9, 8, 6],
            ]),
            $this->buildProduct([
                'name' => 'Zephyr Trail Windbreaker',
                'slug' => 'zephyr-trail-windbreaker',
                'category_slug' => 'windbreakers',
                'collection_slug' => 'desert-air',
                'size_guide_name' => 'Outerwear Standard',
                'description' => 'Windbreaker ultra ringan yang fokus pada perlindungan angin dan kemudahan pack saat aktivitas cepat.',
                'material_names' => ['Coated Polyester', 'Nylon Ripstop'],
                'gender' => 'unisex',
                'weight' => 275,
                'temperature' => 23,
                'intensity' => 'high',
                'insulation' => 24,
                'breathability' => 83,
                'image' => 'products/commuter-windbreaker-primary.svg',
                'sku_prefix' => 'ZTW',
                'price' => 469000,
                'stocks' => [16, 14, 11],
            ]),
            $this->buildProduct([
                'name' => 'Ridge Utility Softshell',
                'slug' => 'ridge-utility-softshell',
                'category_slug' => 'softshell-jackets',
                'collection_slug' => 'ridge-utility',
                'size_guide_name' => 'Outerwear Standard',
                'description' => 'Softshell stretch untuk trek menanjak dan penggunaan teknikal yang butuh mobilitas dan perlindungan ringan.',
                'material_names' => ['Stretch Nylon', 'Elastane'],
                'gender' => 'pria',
                'weight' => 460,
                'temperature' => 14,
                'intensity' => 'high',
                'insulation' => 46,
                'breathability' => 78,
                'image' => 'products/alpine-shield-primary.svg',
                'sku_prefix' => 'RUS',
                'price' => 629000,
                'stocks' => [10, 9, 7],
            ]),
            $this->buildProduct([
                'name' => 'Peak Shelter Parka',
                'slug' => 'peak-shelter-parka',
                'category_slug' => 'insulated-jackets',
                'collection_slug' => 'peak-shelter',
                'size_guide_name' => 'Outerwear Standard',
                'description' => 'Parka tebal dengan rasa hangat yang stabil untuk perjalanan kota dingin dan pemakaian santai di malam hari.',
                'material_names' => ['Recycled Polyester', 'Coated Polyester'],
                'gender' => 'wanita',
                'weight' => 610,
                'temperature' => 0,
                'intensity' => 'low',
                'insulation' => 92,
                'breathability' => 48,
                'image' => 'products/alpine-shield-primary.svg',
                'sku_prefix' => 'PSP',
                'price' => 979000,
                'stocks' => [7, 6, 4],
            ]),
            $this->buildProduct([
                'name' => 'Timber Camp Vest',
                'slug' => 'timber-camp-vest',
                'category_slug' => 'fleece-vests',
                'collection_slug' => 'timber-camp',
                'size_guide_name' => 'Outerwear Standard',
                'description' => 'Vest fleece ringan untuk layering cepat saat pagi dingin di campsite atau perjalanan kasual.',
                'material_names' => ['Polyester Fleece', 'Recycled Polyester'],
                'gender' => 'unisex',
                'weight' => 310,
                'temperature' => 10,
                'intensity' => 'low',
                'insulation' => 68,
                'breathability' => 66,
                'image' => 'products/summit-fleece-primary.svg',
                'sku_prefix' => 'TCV',
                'price' => 489000,
                'stocks' => [13, 11, 9],
            ]),
            $this->buildProduct([
                'name' => 'Summit Shift Pullover',
                'slug' => 'summit-shift-pullover',
                'category_slug' => 'pullover-fleece',
                'collection_slug' => 'summit-shift',
                'size_guide_name' => 'Outerwear Standard',
                'description' => 'Pullover fleece untuk layering di cuaca sejuk dengan handfeel lembut dan bobot yang tetap ringan.',
                'material_names' => ['Polyester Fleece', 'Merino Wool Blend'],
                'gender' => 'unisex',
                'weight' => 390,
                'temperature' => 11,
                'intensity' => 'low',
                'insulation' => 71,
                'breathability' => 63,
                'image' => 'products/summit-fleece-primary.svg',
                'sku_prefix' => 'SSP',
                'price' => 559000,
                'stocks' => [12, 10, 8],
            ]),
            $this->buildProduct([
                'name' => 'Forest Layer Full-Zip',
                'slug' => 'forest-layer-full-zip',
                'category_slug' => 'full-zip-fleece',
                'collection_slug' => 'forest-layer',
                'size_guide_name' => 'Outerwear Standard',
                'description' => 'Full-zip fleece serbaguna untuk layer tengah yang nyaman dipakai dari kota sampai jalur pendek.',
                'material_names' => ['Polyester Fleece', 'Recycled Polyester'],
                'gender' => 'unisex',
                'weight' => 350,
                'temperature' => 12,
                'intensity' => 'low',
                'insulation' => 65,
                'breathability' => 69,
                'image' => 'products/summit-fleece-primary.svg',
                'sku_prefix' => 'FLF',
                'price' => 519000,
                'stocks' => [13, 11, 8],
            ]),
            $this->buildProduct([
                'name' => 'Motion Base Tee',
                'slug' => 'motion-base-tee',
                'category_slug' => 'base-layers',
                'collection_slug' => 'atlas-motion',
                'size_guide_name' => 'Tops Standard',
                'description' => 'Base tee cepat kering yang dibuat untuk aktivitas dinamis dengan feel ringan di kulit.',
                'material_names' => ['Quick-Dry Mesh', 'Recycled Polyester'],
                'gender' => 'unisex',
                'weight' => 160,
                'temperature' => 24,
                'intensity' => 'high',
                'insulation' => 12,
                'breathability' => 94,
                'image' => 'products/trail-sprint-primary.svg',
                'sku_prefix' => 'MBT',
                'price' => 239000,
                'stocks' => [20, 17, 14],
            ]),
            $this->buildProduct([
                'name' => 'Night Run Long Sleeve',
                'slug' => 'night-run-long-sleeve',
                'category_slug' => 'long-sleeve-tops',
                'collection_slug' => 'night-run',
                'size_guide_name' => 'Tops Standard',
                'description' => 'Long sleeve teknikal untuk lari malam atau pagi hari dengan kenyamanan termal yang tetap seimbang.',
                'material_names' => ['Merino Wool Blend', 'Recycled Polyester'],
                'gender' => 'unisex',
                'weight' => 230,
                'temperature' => 18,
                'intensity' => 'high',
                'insulation' => 34,
                'breathability' => 82,
                'image' => 'products/daily-merino-primary.svg',
                'sku_prefix' => 'NRL',
                'price' => 319000,
                'stocks' => [16, 14, 11],
            ]),
            $this->buildProduct([
                'name' => 'Canyon Trail Shirt',
                'slug' => 'canyon-trail-shirt',
                'category_slug' => 'trail-shirts',
                'collection_slug' => 'canyon-light',
                'size_guide_name' => 'Tops Standard',
                'description' => 'Shirt outdoor berpotongan santai untuk trek ringan, travel, dan penggunaan harian yang tetap rapi.',
                'material_names' => ['Stretch Nylon', 'Recycled Polyester'],
                'gender' => 'pria',
                'weight' => 255,
                'temperature' => 20,
                'intensity' => 'low',
                'insulation' => 20,
                'breathability' => 76,
                'image' => 'products/trail-sprint-primary.svg',
                'sku_prefix' => 'CTS',
                'price' => 349000,
                'stocks' => [14, 12, 9],
            ]),
            $this->buildProduct([
                'name' => 'Coastal Breeze Tee',
                'slug' => 'coastal-breeze-tee',
                'category_slug' => 'running-tees',
                'collection_slug' => 'coastal-drizzle',
                'size_guide_name' => 'Tops Standard',
                'description' => 'Tee breathable untuk cuaca panas dengan kemampuan buang panas dan kering cepat yang sangat baik.',
                'material_names' => ['Quick-Dry Mesh', 'Recycled Polyester'],
                'gender' => 'wanita',
                'weight' => 150,
                'temperature' => 28,
                'intensity' => 'high',
                'insulation' => 8,
                'breathability' => 96,
                'image' => 'products/trail-sprint-primary.svg',
                'sku_prefix' => 'CBT',
                'price' => 229000,
                'stocks' => [22, 19, 15],
            ]),
            $this->buildProduct([
                'name' => 'Atlas Trek Pants',
                'slug' => 'atlas-trek-pants',
                'category_slug' => 'hiking-pants',
                'collection_slug' => 'summit-line',
                'size_guide_name' => 'Pants Standard',
                'description' => 'Celana hiking dengan daya tahan baik, stretch secukupnya, dan nyaman dipakai untuk langkah panjang.',
                'material_names' => ['Stretch Nylon', 'Elastane'],
                'gender' => 'pria',
                'weight' => 520,
                'temperature' => 17,
                'intensity' => 'high',
                'insulation' => 38,
                'breathability' => 75,
                'image' => 'products/ridge-cargo-primary.svg',
                'sku_prefix' => 'ATP',
                'price' => 479000,
                'stocks' => [10, 12, 8],
            ]),
            $this->buildProduct([
                'name' => 'Trail Form Shorts',
                'slug' => 'trail-form-shorts',
                'category_slug' => 'shorts',
                'collection_slug' => 'trail-form',
                'size_guide_name' => 'Pants Standard',
                'description' => 'Shorts ringan untuk trail cepat dan sesi latihan luar ruang dengan sirkulasi udara maksimal.',
                'material_names' => ['Stretch Nylon', 'Elastane'],
                'gender' => 'unisex',
                'weight' => 240,
                'temperature' => 27,
                'intensity' => 'high',
                'insulation' => 10,
                'breathability' => 91,
                'image' => 'products/ridge-cargo-primary.svg',
                'sku_prefix' => 'TFS',
                'price' => 299000,
                'stocks' => [18, 16, 13],
            ]),
            $this->buildProduct([
                'name' => 'Nomad Travel Jogger',
                'slug' => 'nomad-travel-jogger',
                'category_slug' => 'joggers',
                'collection_slug' => 'nomad-travel',
                'size_guide_name' => 'Pants Standard',
                'description' => 'Jogger nyaman untuk perjalanan jauh, transit, dan pemakaian harian dengan look yang tetap clean.',
                'material_names' => ['Stretch Nylon', 'Recycled Polyester'],
                'gender' => 'unisex',
                'weight' => 330,
                'temperature' => 19,
                'intensity' => 'low',
                'insulation' => 28,
                'breathability' => 73,
                'image' => 'products/ridge-cargo-primary.svg',
                'sku_prefix' => 'NTJ',
                'price' => 379000,
                'stocks' => [15, 13, 10],
            ]),
            $this->buildProduct([
                'name' => 'Granite Traverse Pant',
                'slug' => 'granite-traverse-pant',
                'category_slug' => 'trail-pants',
                'collection_slug' => 'granite-works',
                'size_guide_name' => 'Pants Standard',
                'description' => 'Trail pants serbaguna dengan keseimbangan mobilitas, bobot, dan durabilitas untuk penggunaan rutin.',
                'material_names' => ['Stretch Nylon', 'Elastane'],
                'gender' => 'pria',
                'weight' => 490,
                'temperature' => 15,
                'intensity' => 'high',
                'insulation' => 35,
                'breathability' => 78,
                'image' => 'products/ridge-cargo-primary.svg',
                'sku_prefix' => 'GTP',
                'price' => 459000,
                'stocks' => [11, 10, 8],
            ]),
            $this->buildProduct([
                'name' => 'Metro Shell Commuter',
                'slug' => 'metro-shell-commuter',
                'category_slug' => 'windbreakers',
                'collection_slug' => 'metro-shell',
                'size_guide_name' => 'Outerwear Standard',
                'description' => 'Shell komuter yang ringan dan mudah dibawa untuk mobilitas kota saat angin dan gerimis datang tiba-tiba.',
                'material_names' => ['Coated Polyester', 'Nylon Ripstop'],
                'gender' => 'wanita',
                'weight' => 305,
                'temperature' => 18,
                'intensity' => 'low',
                'insulation' => 26,
                'breathability' => 72,
                'image' => 'products/commuter-windbreaker-primary.svg',
                'sku_prefix' => 'MSC',
                'price' => 429000,
                'stocks' => [17, 14, 11],
            ]),
            $this->buildProduct([
                'name' => 'Aurora Merino Layer',
                'slug' => 'aurora-merino-layer',
                'category_slug' => 'base-layers',
                'collection_slug' => 'aurora-layer',
                'size_guide_name' => 'Tops Standard',
                'description' => 'Base layer merino blend untuk kenyamanan seharian dengan rasa lembut dan kontrol suhu yang seimbang.',
                'material_names' => ['Merino Wool Blend'],
                'gender' => 'unisex',
                'weight' => 220,
                'temperature' => 13,
                'intensity' => 'low',
                'insulation' => 42,
                'breathability' => 80,
                'image' => 'products/daily-merino-primary.svg',
                'sku_prefix' => 'AML',
                'price' => 339000,
                'stocks' => [15, 12, 10],
            ]),
            $this->buildProduct([
                'name' => 'Horizon Utility Overshirt',
                'slug' => 'horizon-utility-overshirt',
                'category_slug' => 'trail-shirts',
                'collection_slug' => 'horizon-pack',
                'size_guide_name' => 'Tops Standard',
                'description' => 'Overshirt ringan untuk layering santai yang tetap fungsional saat dipakai outdoor ringan atau travel.',
                'material_names' => ['Stretch Nylon', 'Recycled Polyester'],
                'gender' => 'unisex',
                'weight' => 290,
                'temperature' => 22,
                'intensity' => 'low',
                'insulation' => 18,
                'breathability' => 74,
                'image' => 'products/daily-merino-primary.svg',
                'sku_prefix' => 'HUO',
                'price' => 389000,
                'stocks' => [13, 12, 9],
            ]),
            $this->buildProduct([
                'name' => 'Urban Trek Shell Jacket',
                'slug' => 'urban-trek-shell-jacket',
                'category_slug' => 'rain-jackets',
                'collection_slug' => 'urban-trek',
                'size_guide_name' => 'Outerwear Standard',
                'description' => 'Shell jacket serbaguna untuk perjalanan kota dan outdoor ringan dengan tampilan clean dan fungsional.',
                'material_names' => ['Coated Polyester', 'Nylon Ripstop'],
                'gender' => 'unisex',
                'weight' => 410,
                'temperature' => 9,
                'intensity' => 'low',
                'insulation' => 44,
                'breathability' => 79,
                'image' => 'products/alpine-shield-primary.svg',
                'sku_prefix' => 'UTS',
                'price' => 719000,
                'stocks' => [12, 10, 8],
            ]),
        ];
    }

    private function buildProduct(array $product): array
    {
        $sizes = $product['sizes']
            ?? ($product['size_guide_name'] === 'Pants Standard' ? ['30', '32', '34'] : ['S', 'M', 'L']);
        $stocks = $product['stocks'] ?? [12, 10, 8];

        return [
            'name' => $product['name'],
            'slug' => $product['slug'],
            'category_slug' => $product['category_slug'],
            'collection_slug' => $product['collection_slug'],
            'size_guide_name' => $product['size_guide_name'],
            'description' => $product['description'],
            'material_names' => $product['material_names'],
            'gender' => $product['gender'],
            'weight' => $product['weight'],
            'temperature' => $product['temperature'],
            'intensity' => $product['intensity'],
            'insulation' => $product['insulation'],
            'breathability' => $product['breathability'],
            'is_active' => $product['is_active'] ?? true,
            'images' => [
                [
                    'image' => $product['image'],
                    'is_primary' => true,
                    'is_hover' => false,
                ],
            ],
            'variants' => collect($sizes)
                ->values()
                ->map(fn (string $size, int $index) => [
                    'sku' => strtoupper($product['sku_prefix']) . '-' . $size,
                    'size' => $size,
                    'price' => $product['price'],
                    'stock' => $stocks[$index] ?? max(1, 8 - $index),
                ])
                ->all(),
        ];
    }
}
