<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SystemTableSeeder extends Seeder
{
    public function run(): void
    {
        $users = DB::table('users')->orderBy('id')->limit(25)->get(['id', 'email']);
        $timestamp = now()->timestamp;

        foreach ($users as $index => $user) {
            DB::table('password_reset_tokens')->updateOrInsert(
                ['email' => $user->email],
                [
                    'token' => hash('sha256', 'reset-token-' . ($index + 1)),
                    'created_at' => now()->copy()->subMinutes($index),
                ]
            );

            DB::table('sessions')->updateOrInsert(
                ['id' => 'session-' . str_pad((string) ($index + 1), 2, '0', STR_PAD_LEFT)],
                [
                    'user_id' => $user->id,
                    'ip_address' => '192.168.1.' . ($index + 10),
                    'user_agent' => 'SeederBrowser/1.0 (Dummy Session ' . ($index + 1) . ')',
                    'payload' => base64_encode(json_encode([
                        'user_id' => $user->id,
                        'email' => $user->email,
                        'purpose' => 'dummy-session',
                    ])),
                    'last_activity' => $timestamp - ($index * 300),
                ]
            );
        }

        for ($i = 1; $i <= 25; $i++) {
            DB::table('cache')->updateOrInsert(
                ['key' => 'dummy_cache_' . str_pad((string) $i, 2, '0', STR_PAD_LEFT)],
                [
                    'value' => json_encode([
                        'index' => $i,
                        'status' => 'cached',
                        'source' => 'system-seeder',
                    ]),
                    'expiration' => $timestamp + (3600 * $i),
                ]
            );

            DB::table('cache_locks')->updateOrInsert(
                ['key' => 'dummy_lock_' . str_pad((string) $i, 2, '0', STR_PAD_LEFT)],
                [
                    'owner' => 'system-seeder-' . $i,
                    'expiration' => $timestamp + (600 * $i),
                ]
            );

            DB::table('jobs')->updateOrInsert(
                ['id' => $i],
                [
                    'queue' => $i % 2 === 0 ? 'default' : 'emails',
                    'payload' => json_encode([
                        'displayName' => 'DummyJob' . $i,
                        'job' => 'App\\Jobs\\DummyJobHandler',
                        'data' => ['index' => $i],
                    ]),
                    'attempts' => $i % 3,
                    'reserved_at' => $i % 4 === 0 ? $timestamp - 120 : null,
                    'available_at' => $timestamp + ($i * 60),
                    'created_at' => $timestamp - ($i * 30),
                ]
            );

            DB::table('job_batches')->updateOrInsert(
                ['id' => 'batch-' . str_pad((string) $i, 2, '0', STR_PAD_LEFT)],
                [
                    'name' => 'Dummy Batch ' . $i,
                    'total_jobs' => 10 + $i,
                    'pending_jobs' => $i % 5,
                    'failed_jobs' => $i % 4 === 0 ? 1 : 0,
                    'failed_job_ids' => json_encode($i % 4 === 0 ? [$i] : []),
                    'options' => json_encode(['queue' => 'default', 'seed' => true]),
                    'cancelled_at' => null,
                    'created_at' => $timestamp - ($i * 120),
                    'finished_at' => $i % 2 === 0 ? $timestamp - ($i * 60) : null,
                ]
            );

            DB::table('failed_jobs')->updateOrInsert(
                ['uuid' => sprintf('00000000-0000-4000-8000-%012d', $i)],
                [
                    'connection' => 'database',
                    'queue' => $i % 2 === 0 ? 'default' : 'emails',
                    'payload' => json_encode([
                        'displayName' => 'FailedDummyJob' . $i,
                        'job' => 'App\\Jobs\\FailedDummyJobHandler',
                        'data' => ['index' => $i],
                    ]),
                    'exception' => 'Dummy exception #' . $i . ' generated by SystemTableSeeder for testing purposes.',
                    'failed_at' => now()->copy()->subMinutes($i),
                ]
            );
        }
    }
}
